version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - mv $CODEBUILD_SRC_DIR_LAMBDA_BUILD/function.zip function.zip
      - cdk synth BlogApiStack BlogPipelineStack -- -o .
artifacts:
  files:
    - BlogApiStack.template.json
    - BlogPipelineStack.template.json
  base-directory: cdk.out
